# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='degree', to='schedule.Degree'),
        ),
    ]
