# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20160130_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='schedule.Faculty'),
        ),
    ]
