# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20160130_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schedule.Group'),
            preserve_default=False,
        ),
    ]
